[package]
name = "datemon"
version = "0.1.0"
authors = ["Jorg Bornschein <jb@capsec.org>"]
edition = "2018"

[dependencies]
chrono = "0.4"
structopt = "0.2"
stderrlog = "0.4"
log = "0.4"

[profile.release]
opt-level = 3
lto = true
debug = false
codegen-units = 1
panic = "abort"
